export default [
  {
    id: '1',
    title: 'Femergy Founders Club',
    subTitle: 'Invitations Only',
    description: 'Exclusive group for Alpha members',
    icon: '/images/groups-fem-logo.svg',
    disabled: true,
  },
  {
    id: '2',
    title: 'Femergy ICO Participants',
    subTitle: 'Closed Community',
    description: 'All about Femergy ICO',
    isVerified: true,
    icon: '/images/groups-coins.svg',
    disabled: true,
  },
  {
    id: '3',
    title: 'Women in Blockchain',
    subTitle: 'Open Community',
    description: 'Blockchain, cryptocurrency, and tech',
    icon: '/images/groups-2.svg',
    disabled: true,
  },
  {
    id: '4',
    title: 'FEM Ambassadors',
    subTitle: 'Open Community',
    description: 'Exclusive group for FEM ambassadors',
    icon: '/images/groups-1.svg',
    disabled: true,
  },
];
